import { createSlice } from "@reduxjs/toolkit";
import { RootState } from "../../app/store";
import { isAuthenticated } from "./authService";

export interface AuthState {
  email?: string,
  isAuthenticated: boolean
}

const initialState: AuthState = {
  isAuthenticated: false
};

export const authSlice = createSlice({
  name: "auth",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    checkAuth: state => {
      state.email = localStorage.getItem('email') || undefined;
      state.isAuthenticated = isAuthenticated();
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.  
});

export const selectAuth = (state: RootState) => state.auth;

export const { checkAuth } = authSlice.actions;

export default authSlice.reducer;
